# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-09 16:55
from __future__ import unicode_literals

from django.db import migrations, models
import wagtail.wagtailimages.models


class Migration(migrations.Migration):

    dependencies = [
        ('kagiso_image', '0002_auto_20160322_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithattributionrendition',
            name='file',
            field=models.ImageField(height_field='height', upload_to=wagtail.wagtailimages.models.get_rendition_upload_to, width_field='width'),
        ),
    ]
