# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2017-02-02 02:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kagiso_image', '0003_auto_20160809_1655'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagewithattribution',
            name='hyperlink',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='imagewithattributionrendition',
            name='filter_spec',
            field=models.CharField(blank=True, db_index=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='imagewithattributionrendition',
            name='filter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Filter'),
        ),
    ]
