# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kagiso_image', '0005_auto_20170203_0409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagewithattributionrendition',
            name='filter_spec',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='imagewithattributionrendition',
            name='focal_point_key',
            field=models.CharField(blank=True, default='', editable=False, max_length=16),
        ),
        migrations.AlterUniqueTogether(
            name='imagewithattributionrendition',
            unique_together=set([('image', 'filter_spec', 'focal_point_key')]),
        ),
    ]
