# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-12-21 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kagiso_image', '0006_auto_20170203_0417'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagewithattributionrendition',
            name='filter',
        ),
    ]
